
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExampleIV
{

using System;
    using System.Collections.Generic;
    
public partial class C1045817_Astros
{

    public int ID { get; set; }

    public string ClasificacionAstro { get; set; }

    public string TipoSuperficie { get; set; }

    public string Nombre { get; set; }

    public int Edad { get; set; }

    public string Color { get; set; }

    public int RadioPlanetaKm { get; set; }

    public Nullable<int> CantidadLunas { get; set; }

    public Nullable<double> Gravedad { get; set; }

    public Nullable<int> TemperaturaMediaFar { get; set; }

    public Nullable<int> DistanciaSolKm { get; set; }

    public string Foto { get; set; }

}

}
