

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExampleIV
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class nov_jan_2021Entities : DbContext
{
    public nov_jan_2021Entities()
        : base("name=nov_jan_2021Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Student> Student { get; set; }

    public virtual DbSet<C1077982_Ciudadano> C1077982_Ciudadano { get; set; }

    public virtual DbSet<C1045817_Astros> C1045817_Astros { get; set; }

}

}

